depends_on:
  - backend-build

skip_clone: true

labels:
  platform: linux/amd64

steps:
  manifest-cli-branch:
    image: harbor.mindreon.com/ops/woodpeckerci/plugin-docker-buildx:6.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HARBOR_USER: { from_secret: harbor_username }
      HARBOR_PWD: { from_secret: harbor_password }
      REGISTRY: harbor.mindreon.com
      REPO: harbor.mindreon.com/baize/mindreon-cli
    commands:
      - echo $HARBOR_PWD | docker login $REGISTRY -u $HARBOR_USER --password-stdin
      - docker manifest create --amend $REPO:${CI_COMMIT_BRANCH//\//-} $REPO:${CI_COMMIT_BRANCH//\//-}-amd64 $REPO:${CI_COMMIT_BRANCH//\//-}-arm64
      - docker manifest push $REPO:${CI_COMMIT_BRANCH//\//-}
    when:
      event: [push, manual]

  manifest-cli-tag:
    image: harbor.mindreon.com/ops/woodpeckerci/plugin-docker-buildx:6.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HARBOR_USER: { from_secret: harbor_username }
      HARBOR_PWD: { from_secret: harbor_password }
      REGISTRY: harbor.mindreon.com
      REPO: harbor.mindreon.com/baize/mindreon-cli
    commands:
      - echo $HARBOR_PWD | docker login $REGISTRY -u $HARBOR_USER --password-stdin
      - docker manifest create --amend $REPO:$CI_COMMIT_TAG $REPO:$CI_COMMIT_TAG-amd64 $REPO:$CI_COMMIT_TAG-arm64
      - docker manifest push $REPO:$CI_COMMIT_TAG
    when:
      event: tag
